version: "3.8"
services:
  db:
    image: "postgres:13-alpine"
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./databaseScript.sql:/docker-entrypoint-initdb.d/databaseScript.sql
      - postgres_data:/var/lib/postgresql/data/
      - ./data:/data
    networks:
      - fastnetwork

  phonebook_app:
    restart: always
    build:
      context: .
    links:
      - db
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/phonebook_app

    env_file:
      - .env
    depends_on:
      - db
    networks:
      - fastnetwork


volumes:
  postgres_data:
    driver: local

networks:
      fastnetwork:
          driver: bridge
